/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Dir option key-value object */
export interface DirVar {
  key: string
  value: string
}

/** Env option key-value object */
export interface EnvVar {
  key: string
  value?: string
}

/** Run a WebAssembly Component */
export declare function run(runOption: RunOption): void

/** Run a WebAssembly Component configuration option */
export interface RunOption {
  /**
   * Override the value of `argv[0]`, typically the name of the executable of
   * the application being run.
   *
   * This can be useful to pass in situations where a CLI tool is being
   * executed that dispatches its functionality on the value of `argv[0]`
   * without needing to rename the original wasm binary.
   */
  programName?: string
  /** The name of the function to run */
  invoke?: string
  /**
   * Grant access of a host directory to guest root dir.
   *
   * Example: `--work-dir ./`
   */
  workDir?: string
  /**
   * Grant access of a host directory to a guest.
   *
   * Example: `--map-dir ./usr/hello::/hello`
   */
  mapDirs?: Array<DirVar>
  /**
   * Pass an environment variable to the program.
   *
   * Example: `--env FOO=BAR`
   */
  envVars?: Array<EnvVar>
  /**
   * The network destinations which the component is allowed to access.
   * Each entry is in the form "(scheme)://(host)[:port]". Each element
   * allows * as a wildcard e.g. "https://\*" (HTTPS on the default port
   * to any destination) or "\*://localhost:\*" (any protocol to any port on
   * localhost). The host part allows segment wildcards for subdomains
   * e.g. "https://\*.example.com". Application variables are allowed using
   * `{{ my_var }}`` syntax.
   *
   * Example: `--allowed-outbound-hosts https://*.github.net`
   */
  allowedOutboundHosts?: Array<string>
  /**
   * Set of IP networks to be blocked
   *
   * Example: `--block-networks 1.1.1.1/32  -- block-networks private`
   */
  blockNetworks?: Array<string>
  /** Maximum execution time of wasm code before timing out (seconds). */
  wasmTimeout?: number
  /**
   * Maximum size, in bytes, that a linear memory is allowed to reach.
   * Growth beyond this limit will cause memory.grow instructions in
   * WebAssembly components to return -1 and fail.
   */
  wasmMaxMemorySize?: number
  /**
   * Maximum stack size, in bytes, that wasm is allowed to consume before
   * a stack overflow is reported.
   */
  wasmMaxWasmStack?: number
  /**
   * Enable execution fuel with N units fuel, trapping after running out
   * of fuel.
   *
   * Most WebAssembly instructions consume 1 unit of fuel. Some
   * instructions, such as `nop`, `drop`, `block`, and `loop`, consume 0
   * units, as any execution cost associated with them involves other
   * instructions which do consume fuel.
   */
  wasmFuel?: number
  /** Precompiled WebAssembly Component as `*.cwasm` files cache dir. */
  wasmCacheDir?: string
  /** The WebAssembly Component to run */
  wasmFile: string
  /**
   * Arguments passed to the WebAssembly Component will be configured as WASI CLI
   * arguments unless the `--invoke` CLI argument is passed in which case
   * arguments will be interpreted as arguments to the function specified.
   */
  args?: Array<string>
}

/** Start http server from a WebAssembly Component */
export declare function serve(serveOption: ServeOption): void

/** Start http server from a WebAssembly Component configuration option */
export interface ServeOption {
  /** Socket ip for the web server to bind to. */
  ip?: string
  /** Socket port for the web server to bind to. */
  port?: number
  /** Socket port where, when connected to, will initiate a graceful shutdown. */
  shutdownPort?: number
  /**
   * Grant access of a host directory to guest root dir.
   *
   * Example: `--work-dir ./`
   */
  workDir?: string
  /**
   * Grant access of a host directory to a guest.
   *
   * Example: `--map-dir ./usr/hello::/hello`
   */
  mapDirs?: Record<string, string>
  /**
   * Pass an environment variable to the program.
   *
   * Example: `--env FOO=BAR`
   */
  envVars?: Record<string, string | undefined | null>
  /**
   * The network destinations which the component is allowed to access.
   * Each entry is in the form "(scheme)://(host)[:port]". Each element
   * allows * as a wildcard e.g. "https://\*" (HTTPS on the default port
   * to any destination) or "\*://localhost:\*" (any protocol to any port on
   * localhost). The host part allows segment wildcards for subdomains
   * e.g. "https://\*.example.com". Application variables are allowed using
   * `{{ my_var }}`` syntax.
   *
   * Example: `--allowed-outbound-hosts https://*.github.net`
   */
  allowedOutboundHosts?: Array<string>
  /**
   * Set of IP networks to be blocked.
   *
   * Example: `--block-networks 1.1.1.1/32  --block-networks private`
   */
  blockNetworks?: Array<string>
  /**
   * Pass a wasi config variable to the program.
   *
   * Example: `--config-var FOO=BAR`
   */
  configVars?: Array<EnvVar>
  /**
   * Preset data for the In-Memory provider of WASI key-value API.
   *
   * Example: `--keyvalue-var FOO=BAR`
   */
  keyvalueVars?: Array<EnvVar>
  /** Maximum execution time of wasm code before timing out (seconds) */
  wasmTimeout?: number
  /**
   * Maximum size, in bytes, that a linear memory is allowed to reach.
   * Growth beyond this limit will cause memory.grow instructions in
   * WebAssembly Component to return -1 and fail.
   */
  wasmMaxMemorySize?: number
  /**
   * Maximum stack size, in bytes, that wasm is allowed to consume before
   * a stack overflow is reported.
   */
  wasmMaxWasmStack?: number
  /**
   * Enable execution fuel with N units fuel, trapping after running out
   * of fuel.
   *
   * Most WebAssembly instructions consume 1 unit of fuel. Some
   * instructions, such as `nop`, `drop`, `block`, and `loop`, consume 0
   * units, as any execution cost associated with them involves other
   * instructions which do consume fuel.
   */
  wasmFuel?: number
  /** Precompiled WebAssembly Component as `*.cwasm` files cache dir. */
  wasmCacheDir?: string
  /** The WebAssembly Component to run */
  wasmFile: string
}
